language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
  tools:
    ast-grep:
      enabled: true
    fbinfer:
      enabled: true
    biolint:
      enabled: true
chat:
  auto_reply: true
