
const TECH = {
    REACT: "React 18",
    NODE: "Node.js",
    FIREBASE: "Firebase",
    POSTGRES: "Postgres",
    TAILWIND: "Tailwind CSS",
    VITE: "Vite",
    QUERY: "TanStack Query",
    ACTIONS: "GitHub Actions",
    RTDB: "Firebase Realtime Database",
    FIRESTORE: "Firestore"
};

const config = {
    // Phase 1: The Gateway
    entry: {
        title: "Restricted Access",
        subtitle: "Secure connection request detected.",
        message: `This portfolio is a live, operational system—not a static website.
Everything displayed here is generated by real software running in real time. Nothing is simulated, assumed, or manually curated.

What you’re viewing is a moment in the system’s lifecycle, not a frozen snapshot.

This portfolio updates itself. I tried telling it to chill. It didn’t listen 🤭😂`,
        buttonText: "Initialize Live Session"
    },

    // Phase 2: The Handshake
    handshake: {
        steps: [
            "establishing_secure_connection",
            "assigning_session_id", // Updated as requested
            "loading_assets_core",
            "optimizing_experience"
        ],
        completionMessage: "Environment Loaded."
    },

    // Phase 2.5: The Hub (New)
    journey: {
        quickActions: [
            { id: 'PROJECTS', title: "Projects", desc: "Case Studies & Code", icon: "Database" },
            { id: 'SKILLS', title: "Tech Stack", desc: "Skills & Tools", icon: "Cpu" },
            { id: 'ABOUT', title: "About Me", desc: "Bio & Philosophy", icon: "User" },
            { id: 'RESUME', title: "Resume", desc: "Download PDF", icon: "FileText" }
        ]
    },

    // Phase 3: The Dashboard (Hero)
    hero: {
        name: "ADITYA CHAVAN",
        githubUsername: "Aditya-Chavan-dev", // Used for fetching real stats
        role: "Full Stack System Architect",
        tagline: "I don't just write code. I build digital assets that compound in value.",

        // The "Holographic" Identity
        identity: {
            status: "available", // 'available' | 'busy' | 'offline'
            availabilityText: "Available for Hire"
        },

        // The Metrics Ticker
        metrics: {
            loc: {
                label: "Contributions",
                value: 12500,
                suffix: "+"
            },
            commits: {
                label: "Git Commits",
                value: 450
            },
            streak: {
                label: "Github Streak",
                value: 14,
                icon: "fire"
            },
            uptime: {
                label: "System Uptime",
                src: "2024-01-01T00:00:00Z", // Fixed Start Date
                icon: "clock"
            }
        },

        // Tech Stack "Engine"
        stack: [
            { name: TECH.REACT, type: "Core" },
            { name: TECH.NODE, type: "Runtime" },
            { name: TECH.POSTGRES, type: "Database" }
        ]
    },

    // Phase 4: Projects Data
    projects: {
        flagshipRepository: "ATLAS", // Exact match for repo name
        others: {
            excludeForked: true,
            excludeArchived: true
        }
    },

    // Phase 5: Deep Project Metadata (Curated)
    // NOTE: This data is verified against DEPLOYMENT_LOG.md and package.json
    // NOTE: This data is verified against Conversation History (ATLAS Work Logs)
    // NOTE: This data is verified against User-Provided Engineering Logs (Jan 12, 2026)
    projectDetails: {
        "ATLAS": {
            // "Short and Summarized"
            coreIdea: "A Smart Attendance Platform that eliminates the 'Memory Trap' of manual tracking. It replaces the CEO's reliance on memory and Excel sheets with a decentralized, GPS-tagged system where employees mark their own presence, requiring only simple approval.",

            // "Highlight these things"
            tech: {
                frontend: [TECH.REACT, TECH.VITE, TECH.QUERY, TECH.TAILWIND],
                backend: ["Firebase Cloud Functions", TECH.NODE],
                database: [TECH.RTDB + " (WebSockets)", TECH.FIRESTORE],
                versionControl: ["Git", "GitHub Actions", "GitHub"]
            },
            stack: [TECH.REACT, TECH.FIREBASE, TECH.NODE, TECH.TAILWIND, TECH.VITE], // Flattened for UI Badges

            // "Highlight these things: Failures, solutions"
            failures: [
                {
                    id: "f1",
                    title: "The 30x Speedup (Serial vs Parallel)",
                    summary: "Legacy code fetched data day-by-day (serial), causing a 6-second load time.",
                    failure: "The 'My History' tab took ~6 seconds to load because the legacy code was fetching attendance data one day at a time (Serial Fetching). 30 days x 200ms latency = 6000ms wait time.",
                    solution: "Refactored to Parallel Request Aggregation using Promise.all(). We now fire all 30 requests simultaneously.",
                    outcome: "Load time dropped from 6s to ~0.3s. The wait time is now just the speed of one request, not thirty combined."
                },
                {
                    id: "f2",
                    title: "The 'Sunday Rule' Race Condition",
                    summary: "Concurrent leave approvals caused data corruption when users worked on holidays.",
                    failure: "Leave balances were getting corrupted when two approvals happened simultaneously. If a user worked on a Sunday (+1 credit) while taking leave elsewhere, the system would miscount due to a Race Condition.",
                    solution: "Implemented Atomic Transactions (firebaser.runTransaction). This forces the database to process one update at a time, locking the document during the read-write cycle.",
                    outcome: "Achieved 100% Data Integrity. The system guarantees the math is always perfect, regardless of concurrency."
                },
                {
                    id: "f3",
                    title: "The Ad-Blocker Blackout (ERR_BLOCKED)",
                    summary: "Corporate firewalls blocked REST APIs, causing a 10-15% check-in failure rate.",
                    failure: "Corporate firewalls and browser extensions were blocking standard REST API calls, causing 10-15% of users to fail at marking attendance even with internet connection.",
                    solution: "Implemented Protocol Switching. We moved critical checks to use WebSockets via Firebase Realtime Database, which tunnels through standard blockers.",
                    outcome: "100% Availability. The app now acknowledges user input instantly (0ms perceived latency) thanks to Optimistic UI patterns."
                },
                {
                    id: "f4",
                    title: "The White Screen of Death (Cache Rot)",
                    summary: "Stale Service Workers caused app crashes for returning users after breaking changes.",
                    failure: "Users with cached versions of the app experienced white-screen crashes because the new 'Visitor Stats' feature relied on data that didn't exist in their old local storage schema.",
                    solution: "Implemented 'Smart Hydration' and a Service Worker Kill-Switch. The app now detects schema mismatches and auto-wipes stale cache before React mounts.",
                    outcome: "Zero crash reports on deployment. The system self-heals legacy state without requiring the user to manually clear browser data."
                }
            ],

            // "Short and Summarized"
            timeline: [
                { year: "2026", event: "Work In Progress (WIP)" },
                { year: "2025", event: "Dec 6: Project Start" },
            ],

            // New: Demo Link
            demoUrl: "#", // Placeholder for actual demo link

            // New: Flagship Features (Expandable)
            features: [
                {
                    title: "GPS-Fenced Attendance",
                    what: "Verifies employee presence using the Geolocation API, validating coordinates against a defined geofence radius before allowing check-in.",
                    tech: "HTML5 Geolocation API, Haversine Formula, Firebase Cloud Functions",
                    security: "Prevents location spoofing by cross-referencing IP-based location (when available) and rejecting high-accuracy discrepancies.",
                    tip: "Users tried spoofing GPS on Android. We added a server-side distance check that auto-flags 'impossibly fast' travel."
                },
                {
                    title: "Offline-First Architecture",
                    what: "Allows full app functionality without internet. Attendance logs are queued locally in IndexedDB and background-synced when connectivity returns.",
                    tech: "Service Workers (Workbox), IndexedDB, Background Sync API",
                    security: "Local data is encrypted. Timestamps are server-validated upon sync to prevent local time manipulation.",
                    tip: "The hardest part wasn't storing data, it was resolving merge conflicts when a user modified their state on two offline devices."
                },
                {
                    title: "Protocol Switching (Anti-Blocker)",
                    what: "Detects 'ERR_BLOCKED' on REST endpoints (common in corporate firewalls) and instantly tunnels traffic via WebSockets (Firebase RTDB) instead.",
                    tech: "Axios Interceptors, Firebase Realtime Database SDK",
                    security: "Maintains full SSL/TLS encryption regardless of the transport layer used.",
                    tip: "Corporate firewalls love blocking POST requests to unknown APIs, but they almost never block port 443 WebSockets."
                },
                {
                    title: "One-Tap Check-in",
                    what: "Delivers 0ms perceived latency using Optimistic UI. The UI confirms the action immediately while the backend processes the transaction asynchronously.",
                    tech: "React Query (TanStack Query) Optimistic Updates",
                    security: "Rate limiting prevents button mashing. Rollback UI handles rare server rejections gracefully.",
                    tip: "We reduced 'Did it work?' support tickets by 90% just by making the button turn green instantly."
                }
            ]
        }
    },

    // Global Configuration
    apiBaseUrl: import.meta.env.VITE_API_URL || ""
};

export default config;
