
import { ATLAS_DATA } from './data/projects/atlas';

const TECH = {
    REACT: "React 18",
    NODE: "Node.js",
    FIREBASE: "Firebase",
    POSTGRES: "Postgres",
    TAILWIND: "Tailwind CSS",
    VITE: "Vite",
    QUERY: "TanStack Query",
    ACTIONS: "GitHub Actions",
    RTDB: "Firebase Realtime Database",
    FIRESTORE: "Firestore"
};

const config = {
    // Phase 1: The Gateway
    entry: {
        title: "Restricted Access",
        subtitle: "Secure connection request detected.",
        message: `This portfolio is a live, operational system—not a static website.
Everything displayed here is generated by real software running in real time. Nothing is simulated, assumed, or manually curated.

What you’re viewing is a moment in the system’s lifecycle, not a frozen snapshot.

This portfolio updates itself. I tried telling it to chill. It didn’t listen 🤭😂`,
        buttonText: "Initialize Live Session"
    },

    // Phase 2: The Handshake
    handshake: {
        steps: [
            "establishing_secure_connection",
            "assigning_session_id", // Updated as requested
            "loading_assets_core",
            "optimizing_experience"
        ],
        completionMessage: "Environment Loaded."
    },

    // Phase 2.5: The Hub (New)
    journey: {
        quickActions: [
            { id: 'PROJECTS', title: "Projects", desc: "Case Studies & Code", icon: "Database" },
            { id: 'SKILLS', title: "Tech Stack", desc: "Skills & Tools", icon: "Cpu" },
            { id: 'ABOUT', title: "About Me", desc: "Bio & Philosophy", icon: "User" },
            { id: 'RESUME', title: "Resume", desc: "Download PDF", icon: "FileText" }
        ]
    },

    // Phase 3: The Dashboard (Hero)
    hero: {
        name: "ADITYA CHAVAN",
        githubUsername: "Aditya-Chavan-dev", // Used for fetching real stats
        role: "Full Stack System Architect",
        tagline: "I don't just write code. I build digital assets that compound in value.",

        // The "Holographic" Identity
        identity: {
            status: "available", // 'available' | 'busy' | 'offline'
            availabilityText: "Available for Hire"
        },

        // The Metrics Ticker
        metrics: {
            loc: {
                label: "Contributions",
                value: 12500,
                suffix: "+"
            },
            commits: {
                label: "Git Commits",
                value: 450
            },
            streak: {
                label: "Github Streak",
                value: 14,
                icon: "fire"
            },
            uptime: {
                label: "System Uptime",
                src: "2024-01-01T00:00:00Z", // Fixed Start Date
                icon: "clock"
            }
        },

        // Tech Stack "Engine"
        stack: [
            { name: TECH.REACT, type: "Core" },
            { name: TECH.NODE, type: "Runtime" },
            { name: TECH.POSTGRES, type: "Database" }
        ]
    },

    // Phase 4: Projects Data
    projects: {
        flagshipRepository: "ATLAS", // Exact match for repo name
        others: {
            excludeForked: true,
            excludeArchived: true
        }
    },

    // Phase 5: Deep Project Metadata (Curated)
    // NOTE: This data is verified against DEPLOYMENT_LOG.md and package.json
    // NOTE: This data is verified against Conversation History (ATLAS Work Logs)
    // NOTE: This data is verified against User-Provided Engineering Logs (Jan 12, 2026)
    projectDetails: {
        "ATLAS": ATLAS_DATA
    },

    // Global Configuration
    apiBaseUrl: import.meta.env.VITE_API_URL || ""
};

export default config;
