
const config = {
    // Phase 1: The Gateway
    entry: {
        title: "Restricted Access",
        subtitle: "Secure connection request detected.",
        message: `This portfolio is a live, operational system—not a static website.
Everything displayed here is generated by real software running in real time. Nothing is simulated, assumed, or manually curated.

What you’re viewing is a moment in the system’s lifecycle, not a frozen snapshot.

This portfolio updates itself. I tried telling it to chill. It didn’t listen 🤭😂`,
        buttonText: "Initialize Live Session"
    },

    // Phase 2: The Handshake
    handshake: {
        steps: [
            "establishing_secure_connection",
            "assigning_session_id", // Updated as requested
            "loading_assets_core",
            "optimizing_experience"
        ],
        completionMessage: "Environment Loaded."
    },

    // Phase 3: The Dashboard (Hero)
    hero: {
        name: "ADITYA CHAVAN",
        githubUsername: "Aditya-Chavan-dev", // Used for fetching real stats
        role: "Full Stack System Architect",
        tagline: "I don't just write code. I build digital assets that compound in value.",

        // The "Holographic" Identity
        identity: {
            status: "available", // 'available' | 'busy' | 'offline'
            availabilityText: "Available for Hire"
        },

        // The Metrics Ticker
        metrics: {
            loc: {
                label: "Contributions",
                value: 12500,
                suffix: "+"
            },
            commits: {
                label: "Git Commits",
                value: 450
            },
            streak: {
                label: "Github Streak",
                value: 14,
                icon: "fire"
            },
            uptime: {
                label: "System Uptime",
                src: "2024-01-01T00:00:00Z", // Fixed Start Date
                icon: "clock"
            }
        },

        // Tech Stack "Engine"
        stack: [
            { name: "React 18", type: "Core" },
            { name: "Node.js", type: "Runtime" },
            { name: "Postgres", type: "Database" }
        ]
    },

    // Phase 4: Projects Data
    projects: {
        flagshipRepository: "ATLAS", // Exact match for repo name
        others: {
            excludeForked: true,
            excludeArchived: true
        }
    },

    // Phase 5: Deep Project Metadata (Curated)
    // Phase 5: Deep Project Metadata (Curated)
    // NOTE: This data is verified against DEPLOYMENT_LOG.md and package.json
    // Phase 5: Deep Project Metadata (Curated)
    // NOTE: This data is verified against Conversation History (ATLAS Work Logs)
    // NOTE: This data is verified against User-Provided Engineering Logs (Jan 12, 2026)
    projectDetails: {
        "ATLAS": {
            // "Short and Summarized"
            coreIdea: "A Smart Attendance Platform that eliminates the 'Memory Trap' of manual tracking. It replaces the CEO's reliance on memory and Excel sheets with a decentralized, GPS-tagged system where employees mark their own presence, requiring only simple approval.",

            // "Highlight these things"
            tech: {
                frontend: ["React 18", "Vite", "TanStack Query", "Tailwind CSS"],
                backend: ["Firebase Cloud Functions", "Node.js"],
                database: ["Firebase Realtime Database (WebSockets)", "Firestore"],
                infrastructure: ["Firebase Hosting", "GitHub Actions"]
            },

            // "Highlight these things: Failures, solutions"
            failures: [
                {
                    id: "f1",
                    title: "The 30x Speedup (Serial vs Parallel)",
                    summary: "Legacy code fetched data day-by-day (serial), causing a 6-second load time.",
                    failure: "The 'My History' tab took ~6 seconds to load because the legacy code was fetching attendance data one day at a time (Serial Fetching). 30 days x 200ms latency = 6000ms wait time.",
                    solution: "Refactored to Parallel Request Aggregation using Promise.all(). We now fire all 30 requests simultaneously.",
                    outcome: "Load time dropped from 6s to ~0.3s. The wait time is now just the speed of one request, not thirty combined."
                },
                {
                    id: "f2",
                    title: "The 'Sunday Rule' Race Condition",
                    summary: "Concurrent leave approvals caused data corruption when users worked on holidays.",
                    failure: "Leave balances were getting corrupted when two approvals happened simultaneously. If a user worked on a Sunday (+1 credit) while taking leave elsewhere, the system would miscount due to a Race Condition.",
                    solution: "Implemented Atomic Transactions (firebaser.runTransaction). This forces the database to process one update at a time, locking the document during the read-write cycle.",
                    outcome: "Achieved 100% Data Integrity. The system guarantees the math is always perfect, regardless of concurrency."
                },
                {
                    id: "f3",
                    title: "The Ad-Blocker Blackout (ERR_BLOCKED)",
                    summary: "Corporate firewalls blocked REST APIs, causing a 10-15% check-in failure rate.",
                    failure: "Corporate firewalls and browser extensions were blocking standard REST API calls, causing 10-15% of users to fail at marking attendance even with internet connection.",
                    solution: "Implemented Protocol Switching. We moved critical checks to use WebSockets via Firebase Realtime Database, which tunnels through standard blockers.",
                    outcome: "100% Availability. The app now acknowledges user input instantly (0ms perceived latency) thanks to Optimistic UI patterns."
                }
            ],

            // "Short and Summarized"
            // "Short and Summarized"
            timeline: [
                { year: "2026", event: "Work In Progress (WIP)" },
                { year: "2025", event: "Dec 6: Project Start" },
            ],

            // New: Demo Link
            demoUrl: "#", // Placeholder for actual demo link

            // New: Flagship Features (Expandable)
            features: [
                {
                    title: "GPS-Fenced Attendance",
                    what: "Placeholder: Simple explanation of what this feature does",
                    tech: "Placeholder: Technologies used to build this",
                    security: "Placeholder: Security assessment and potential exploits",
                    tip: "Placeholder: War story tip (1-2 lines with humor)"
                },
                {
                    title: "Offline-First Architecture",
                    what: "Placeholder: Simple explanation of what this feature does",
                    tech: "Placeholder: Technologies used to build this",
                    security: "Placeholder: Security assessment and potential exploits",
                    tip: "Placeholder: War story tip (1-2 lines with humor)"
                },
                {
                    title: "Protocol Switching (Anti-Blocker)",
                    what: "Placeholder: Simple explanation of what this feature does",
                    tech: "Placeholder: Technologies used to build this",
                    security: "Placeholder: Security assessment and potential exploits",
                    tip: "Placeholder: War story tip (1-2 lines with humor)"
                },
                {
                    title: "One-Tap Check-in",
                    what: "Placeholder: Simple explanation of what this feature does",
                    tech: "Placeholder: Technologies used to build this",
                    security: "Placeholder: Security assessment and potential exploits",
                    tip: "Placeholder: War story tip (1-2 lines with humor)"
                }
            ]
        }
    },

    // Global Configuration
    apiBaseUrl: import.meta.env.VITE_API_URL || ""
};

export default config;
